  on:
    - push
    - pull_request

  jobs:
    lint:
      name: Linting
      runs-on: ubuntu-latest

      steps:
        - name: Checkout repository
          uses: actions/checkout@v3

        - name: Configure cache
          uses: actions/cache@v3
          with:
            path: |
              ~/.cache/black
              ~/.cache/pip
              ./.ruff_cache
              ./.mypy_cache
            key: ${{ runner.os }}-lint-
            restore-keys: ${{ runner.os }}-lint-

        - name: Install Python
          uses: actions/setup-python@v4
          with:
            python-version: "3.11"

        - name: Install dependencies
          run: pip install -r requirements.txt

        - name: Lint with ruff
          if: always()
          run: ruff library

        - name: Lint with black
          if: always()
          run: black library --check

        - name: Typecheck with mypy
          if: always()
          run: mypy library
